#!/bin/bash

set -o errexit
set -o pipefail
set -o nounset


{% if cookiecutter.use_celery == 'y' %}
# N.B. If only .env files supported variable expansion...
export CELERY_BROKER_URL="${REDIS_URL}"
{% endif %}

export DATABASE_URL="mysql://${MYSQL_HOST}:${MYSQL_PORT}/${MYSQL_DB}?user=${MYSQL_USER}&password=${MYSQL_PASSWORD}"

mysql_ready() {
python << END
import sys

import MySQLdb

try:
    MySQLdb.connect(
        host="${MYSQL_HOST}",
        user="${MYSQL_USER}",
        password="${MYSQL_PASSWORD}",
        port=${MYSQL_PORT},
    )
except MySQLdb.OperationalError as e:
    print(str(e))
    sys.exit(-1)
sys.exit(0)

END
}
until mysql_ready; do
  >&2 echo 'Waiting for MySQL to become available...'
  sleep 1
done
>&2 echo 'MySQL is available'

exec "$@"
