exclude: 'docs|node_modules|migrations|.git|.tox'
default_stages: [commit]
fail_fast: true

repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.0.1
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml

  - repo: https://github.com/psf/black
    rev: 21.9b0
    hooks:
      - id: black
        language_version: python3.6

  - repo: https://github.com/pycqa/isort.git
    rev: 4.3.21
    hooks:
      - id: isort
        language_version: python3.6
        additional_dependencies: [toml]

  - repo: https://gitlab.com/pycqa/flake8.git
    rev: 3.7.9
    hooks:
      - id: flake8
        language_version: python3.6
        additional_dependencies: [flake8-isort]
        args: ['--config=setup.cfg', '--disable-noqa', '--ignore=F401,F403,F405,W503,W605']


# sets up .pre-commit-ci.yaml to ensure pre-commit dependencies stay up to date
ci:
    autoupdate_schedule: weekly
    skip: []
    submodules: false
