release: python manage.py migrate
{% if cookiecutter.use_async == "y" -%}
web: gunicorn {{cookiecutter.project_slug}}.asgi:application -k uvicorn.workers.UvicornWorker
{%- else %}
web: gunicorn {{cookiecutter.project_slug}}.wsgi:application
{%- endif %}
{% if cookiecutter.use_celery == "y" -%}
worker: REMAP_SIGTERM=SIGQUIT celery -A {{cookiecutter.project_slug}}.celery_app worker --loglevel=info
beat: REMAP_SIGTERM=SIGQUIT celery -A {{cookiecutter.project_slug}}.celery_app beat --loglevel=info
{%- endif %}
