version: '3'

volumes:
  production_mysql_data: {}
  production_traefik: {}

services:
  {{ cookiecutter.project_slug }}:{% if cookiecutter.use_celery == 'y' %} &{{ cookiecutter.project_slug }}{% endif %}
    build:
      context: .
      dockerfile: ./compose/production/django/Dockerfile
    image: {{ cookiecutter.project_slug }}_production_django
    depends_on:
      - mysql
      - redis
    env_file:
      - ./.envs/.production/.django
      - ./.envs/.production/.mysql
    command: /start

  mysql:
    image: jumpserver/mysql:5
    container_name: {{ cookiecutter.project_slug }}_production_mysql
    environment:
      DB_PORT: $MYSQL_PORT
      MYSQL_ROOT_PASSWORD: $MYSQL_PASSWORD
      MYSQL_DATABASE: $MYSQL_DB
    volumes:
      - ./compose/production/mysql/my.cnf:/etc/mysql/my.cnf
      - production_mysql_data:/var/lib/mysql:Z
    env_file:
      - ./.envs/.production/.mysql
    command: --character-set-server=utf8
    healthcheck:
      test: "mysql -h127.0.0.1 -P$$DB_PORT -uroot -p$$MYSQL_ROOT_PASSWORD -e 'SHOW DATABASES;'"
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 30s

  traefik:
    build:
      context: .
      dockerfile: ./compose/production/traefik/Dockerfile
    image: {{ cookiecutter.project_slug }}_production_traefik
    depends_on:
      - {{ cookiecutter.project_slug }}
    volumes:
      - production_traefik:/etc/traefik/acme:z
    ports:
      - "0.0.0.0:80:80"
      - "0.0.0.0:443:443"
      {%- if cookiecutter.use_celery == 'y' %}
      - "0.0.0.0:5555:5555"
      {%- endif %}

  redis:
    image: redis:6
    container_name: {{ cookiecutter.project_slug }}_production_redis
  {%- if cookiecutter.use_celery == 'y' %}

  celeryworker:
    <<: *{{ cookiecutter.project_slug }}
    image: {{ cookiecutter.project_slug }}_production_celeryworker
    command: /start-celeryworker

  celerybeat:
    <<: *{{ cookiecutter.project_slug }}
    image: {{ cookiecutter.project_slug }}_production_celerybeat
    command: /start-celerybeat

  flower:
    <<: *{{ cookiecutter.project_slug }}
    image: {{ cookiecutter.project_slug }}_production_flower
    command: /start-flower
  {%- endif %}
  {%- if cookiecutter.cloud_provider == 'AWS' %}

  awscli:
    build:
      context: .
      dockerfile: ./compose/production/aws/Dockerfile
    env_file:
      - ./.envs/.production/.django
  {%- endif %}
